name: Deploy Docker Image with Optional Docker Install

on:
  workflow_dispatch:
    inputs:
      install_docker:
        description: "Install Docker if not present"
        required: true
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Install Docker if Necessary
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # Check if Docker is installed
            if ! [ -x "$(command -v docker)" ]; then
              echo "Docker is not installed."
              if [[ "${{ inputs.install_docker }}" == "true" ]]; then
                echo "Installing Docker..."
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
              else
                echo "Docker installation skipped. Exiting..."
                exit 1
              fi
            else
              echo "Docker is already installed."
            fi

      - name: SSH into Server and Deploy Docker Container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # Pull the latest Docker image and run it with the host's PID namespace
            docker pull ${{ secrets.DOCKER_USERNAME }}/zomboid-crash-monitor:latest
            docker run --pid=host -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
              -e DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }} \
              -e ZOMBOID_SERVICE_NAME=${{ secrets.ZOMBOID_SERVICE_NAME }} \
              ${{ secrets.DOCKER_USERNAME }}/zomboid-crash-monitor:latest